package:
    name: psrchive
    version: {{ os.environ.get('VERSION') }} 

source:
    # Assumes source has been checkout out here:
    path: ../psrchive
        
build:
    number: 1

test:
    imports:
        - psrchive

requirements:
    build:
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - {{ compiler('fortran') }}
        - autoconf
        - automake
        - libtool
        - swig
    host:
        - cfitsio
        - pgplot
        - gsl
        - python {{ python }}
        - numpy
        - fftw
        - epsic
    run:
        - cfitsio
        - pgplot
        - gsl
        - python
        - numpy
        - tempo
        - fftw
        - epsic
