package:
    name: psrchive
    version: {{ os.environ.get('VERSION') }} 

source:
    # Assumes source has been checkout out here:
    path: ../psrchive
        
build:
    number: 1
    script_env:
        - TRAVIS_OS_NAME

test:
    commands:
        - pav -h
    imports:
        - psrchive

requirements:
    build:
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - {{ compiler('fortran') }}
        - autoconf
        - automake
        - libtool
        - swig
    host:
        - cfitsio
        - pgplot
        - gsl
        - python {{ python }}
        - numpy
        - fftw
        - tempo2
    run:
        - cfitsio
        - pgplot
        - gsl
        - python
        - numpy
        - tempo
        - tempo2
        - fftw
